--- 
clone: 
  depth: 1
kind: pipeline
name: ReinaPipeline
steps: 
  - 
    commands: 
      - "curl https://raw.githubusercontent.com/Reinazhard/myscripts/sadtoni/kernel.sh | bash"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
    image: fadlyas/kernel_dockerfile:latest
    name: Zhard-Lair
